/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.movago.forms;

import com.movago.Trip;
import com.movago.User;

/**
 *
 * @author Arca
 */
public class TripPage extends javax.swing.JPanel {
    Trip trip;
    User user;
    /**
     * Creates new form TripPage
     */
    public TripPage(Trip trip, User user) {
        this.trip = trip;
        this.user = user;
        String html = "<table style=\"height: 177px; width: 99.0683%; border-collapse: collapse; border-style: dotted; float: left;\" border=\"1\">\n" +
"<tbody>\n" +
"<tr style=\"height: 177px;\">\n" +
"<td style=\"width: 73.3194%; height: 177px;\">"+user.getBio()+"</td>\n" +
"<td style=\"width: 48.9028%; height: 177px;\">\n" +
"<p><img src=\"https://media.licdn.com/dms/image/D4E03AQFO-ZTrzm3DgA/profile-displayphoto-shrink_800_800/0/1713032291243?e=1720656000&amp;v=beta&amp;t=lv1VFBF5z5tqYXPWdT18ntafsHBQlNB4zJs_BQJLJY4\" alt=\"\" width=\"169\" height=\"169\" />Name:&nbsp;"+ user.getUserName()+" &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;75</p>\n" +
"</td>\n" +
"</tr>\n" +
"</tbody>\n" +
"</table>\n" +
"<p style=\"text-align: center;\"><strong>"+trip.getFrom()+"</strong>&nbsp; &nbsp; ✈&nbsp; &nbsp; <strong>Arrival: "+trip.getCity()+"</strong>&nbsp; &nbsp; ✈&nbsp; &nbsp; <strong>Arrival: "+trip.getCity2()+"&nbsp;</strong>&nbsp; &nbsp;✈&nbsp; &nbsp;<strong>Final Destination: "+trip.getCity3()+"</strong></p>\n" +
"<p style=\"text-align: left;\">&nbsp;</p>\n" +
"<ul>\n" +
"<li style=\"text-align: left;\"><strong>&nbsp; &nbsp; "+trip.getCity()+":</strong>\n" +
"<ul>\n" +
"<li style=\"text-align: left;\">"+trip.getAccommodation()+" / "+trip.getfirstDate()+" - "+trip.getDate()+"</li>\n" +
"<li style=\"text-align: left;\">Budget: "+trip.getBudget()+"/li>\n" +
"</ul>\n" +
"</li>\n" +
"</ul>\n" +
"<p>&nbsp;</p>\n" +
"<ul>\n" +
"<li>&nbsp;<strong> &nbsp; "+trip.getCity2()+":</strong>\n" +
"<ul>\n" +
"<li>"+trip.getAccommodation2()+" / "+trip.getDate()+" - "+trip.getDate2()+"</li>\n" +
"<li>Budget: "+trip.getBudget2()+"</li>\n" +
"</ul>\n" +
"</li>\n" +
"</ul>\n" +
"<p>&nbsp;</p>\n" +
"<ul>\n" +
"<li>&nbsp; &nbsp; <strong>"+trip.getCity3()+":</strong>\n" +
"<ul>\n" +
"<li>"+trip.getAccommodation3()+" / "+trip.getDate2()+"- "+trip.getDate3()+"/li>\n" +
"<li>Budget: "+trip.getBudget3()+"</li>\n" +
"</ul>\n" +
"</li>\n" +
"</ul>\n" +
"<p>&nbsp;</p>\n" +
"<p><strong>Total Budget: "+trip.getTotalBudget()+"</strong></p>";
        
        initComponents();
        jTextPane1.setContentType("text/html");
        jTextPane1.setText(html);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText(trip.getTitle());

        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 137, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
